exploration_node:
  ros__parameters:
    "sdf_map/resolution": 0.1
    "sdf_map/map_size_x": 40.0
    "sdf_map/map_size_y": 20.0
    "sdf_map/map_size_z": 5.0
    "sdf_map/obstacles_inflation": 0.199
    "sdf_map/local_bound_inflate": 0.5
    "sdf_map/local_map_margin": 50
    "sdf_map/ground_height": -1.0
    "sdf_map/default_dist": 0.0
    "sdf_map/p_hit": 0.65
    "sdf_map/p_miss": 0.35
    "sdf_map/p_min": 0.12
    "sdf_map/p_max": 0.90
    "sdf_map/p_occ": 0.80
    "sdf_map/min_ray_length": 0.5
    "sdf_map/max_ray_length": 4.5
    "sdf_map/virtual_ceil_height": -10.0
    "sdf_map/optimistic": false
    "sdf_map/signed_dist": false
    "sdf_map/box_min_x": -20.0
    "sdf_map/box_min_y": -10.0
    "sdf_map/box_min_z": 0.0
    "sdf_map/box_max_x": 20.0
    "sdf_map/box_max_y": 10.0
    "sdf_map/box_max_z": 2.0

    "map_ros/cx": 321.04638671875
    "map_ros/cy": 243.44969177246094
    "map_ros/fx": 387.229248046875
    "map_ros/fy": 387.229248046875
    "map_ros/depth_filter_maxdist": 5.0
    "map_ros/depth_filter_mindist": 0.2
    "map_ros/depth_filter_margin": 2
    "map_ros/k_depth_scaling_factor": 1000.0
    "map_ros/skip_pixel": 2
    "map_ros/esdf_slice_height": 0.3
    "map_ros/visualization_truncate_height": 10.09
    "map_ros/visualization_truncate_low": -2.0
    "map_ros/show_occ_time": false
    "map_ros/show_esdf_time": false
    "map_ros/show_all_map": true
    "map_ros/frame_id": "world"

    "fsm/thresh_replan1": 0.5
    "fsm/thresh_replan2": 0.5
    "fsm/thresh_replan3": 1.5
    "fsm/replan_time": 0.200

    "exploration/refine_local": true
    "exploration/refined_num": 7
    "exploration/refined_radius": 5.0
    "exploration/max_decay": 0.8
    "exploration/top_view_num": 15
    "exploration/vm": 2.0
    "exploration/am": 2.0
    "exploration/yd": 1.047
    "exploration/ydd": 1.57
    "exploration/w_dir": 1.5
    # tsp_dir set in launch file using FindPackageShare
    "exploration/relax_time": 1.0

    "frontier/cluster_min": 100
    "frontier/cluster_size_xy": 2.0
    "frontier/cluster_size_z": 10.0
    "frontier/min_candidate_dist": 0.75
    "frontier/min_candidate_clearance": 0.21
    "frontier/candidate_dphi": 0.2618
    "frontier/candidate_rnum": 3
    "frontier/candidate_rmin": 1.5
    "frontier/candidate_rmax": 2.5
    "frontier/down_sample": 3
    "frontier/min_visib_num": 15
    "frontier/min_view_finish_fraction": 0.2

    "perception_utils/top_angle": 0.56125
    "perception_utils/left_angle": 0.69222
    "perception_utils/right_angle": 0.68901
    "perception_utils/max_dist": 4.5
    "perception_utils/vis_dist": 1.0

    "heading_planner/yaw_diff": 0.5235
    "heading_planner/half_vert_num": 5
    "heading_planner/lambda1": 2.0
    "heading_planner/lambda2": 1.0
    "heading_planner/max_yaw_rate": 0.1745
    "heading_planner/w": 20000.0
    "heading_planner/weight_type": 1

    "manager/max_vel": 2.0
    "manager/max_acc": 2.0
    "manager/max_jerk": 4.0
    "manager/dynamic_environment": 0
    "manager/local_segment_length": 6.0
    "manager/clearance_threshold": 0.2
    "manager/control_points_distance": 0.35
    "manager/use_geometric_path": true
    "manager/use_kinodynamic_path": true
    "manager/use_topo_path": true
    "manager/use_optimization": true
    "manager/use_active_perception": true
    "manager/min_time": true

    "search/max_tau": 0.8
    "search/init_max_tau": 1.0
    "search/max_vel": 2.0
    "search/vel_margin": 0.25
    "search/max_acc": 2.0
    "search/w_time": 10.0
    "search/horizon": 5.0
    "search/lambda_heu": 10.0
    "search/resolution_astar": 0.025
    "search/time_resolution": 0.8
    "search/margin": 0.2
    "search/allocate_num": 100000
    "search/check_num": 10
    "search/optimistic": false

    "astar/lambda_heu": 10000.0
    "astar/resolution_astar": 0.2
    "astar/allocate_num": 1000000
    "astar/max_search_time": 0.001

    "optimization/ld_smooth": 20.0
    "optimization/ld_dist": 10.0
    "optimization/ld_feasi": 2.0
    "optimization/ld_start": 100.0
    "optimization/ld_end": 0.5
    "optimization/ld_guide": 1.5
    "optimization/ld_waypt": 0.3
    "optimization/ld_view": 0.0
    "optimization/ld_time": 1.0
    "optimization/dist0": 0.7
    "optimization/max_vel": 2.0
    "optimization/max_acc": 2.0
    "optimization/algorithm1": 15
    "optimization/algorithm2": 11
    "optimization/max_iteration_num1": 2
    "optimization/max_iteration_num2": 2000
    "optimization/max_iteration_num3": 200
    "optimization/max_iteration_num4": 200
    "optimization/max_iteration_time1": 0.0001
    "optimization/max_iteration_time2": 0.005
    "optimization/max_iteration_time3": 0.003
    "optimization/max_iteration_time4": 0.003

    "bspline/limit_vel": 2.0
    "bspline/limit_acc": 2.0
    "bspline/limit_ratio": 1.1