mppi_control:
  ros__parameters:
    mppi:
      K: 1000
      H: 20
      dt: 0.05
      sigma: 0.2
      lambda: 0.1
      Q_pos: 20.0
      Q_vel: 2.0
      R: 0.1
      w_obs: 100.0
      a_max: 10.0
      tilt_max: 0.6
      g: 9.81
    mass: 0.98
