mppi_control:
  ros__parameters:
    mppi:
      K: 9000
      H: 50
      dt: 0.02
      sigma: 0.2
      lambda: 0.01
      Q_pos_x: 50.0
      Q_pos_y: 50.0
      Q_pos_z: 50.0
      Q_vel_x: 2.0
      Q_vel_y: 2.0
      Q_vel_z: 2.0
      R_x: 0.1
      R_y: 0.1
      R_z: 0.1
      R_rate_x: 10.0
      R_rate_y: 10.0
      R_rate_z: 10.0
      w_obs: 20.0
      a_max: 10.0
      tilt_max: 0.6
      g: 9.81
    mass: 0.98
