fast_planner_node:
  ros__parameters:
    "planner_node/planner": 1

    "fsm/flight_type": 2
    "fsm/thresh_replan": 1.5
    "fsm/thresh_no_replan": 2.0
    "fsm/waypoint_num": 1
    "fsm/waypoint0_x": 19.0
    "fsm/waypoint0_y": 0.0
    "fsm/waypoint0_z": 1.0
    "fsm/waypoint1_x": 19.9
    "fsm/waypoint1_y": 0.0
    "fsm/waypoint1_z": 1.0
    "fsm/waypoint2_x": 0.0
    "fsm/waypoint2_y": 19.0
    "fsm/waypoint2_z": 1.0
    "fsm/act_map": false

    "sdf_map/resolution": 0.1
    "sdf_map/map_size_x": 40.0
    "sdf_map/map_size_y": 20.0
    "sdf_map/map_size_z": 5.0
    "sdf_map/obstacles_inflation": 0.099
    "sdf_map/local_bound_inflate": 0.5
    "sdf_map/local_map_margin": 50.0
    "sdf_map/ground_height": -1.0
    "sdf_map/default_dist": 5.0
    "sdf_map/p_hit": 0.65
    "sdf_map/p_miss": 0.43
    "sdf_map/p_min": 0.12
    "sdf_map/p_max": 0.9
    "sdf_map/p_occ": 0.8
    "sdf_map/min_ray_length": 0.5
    "sdf_map/max_ray_length": 4.5
    "sdf_map/virtual_ceil_height": 3.2
    "sdf_map/optimistic": true
    "sdf_map/signed_dist": false

    "map_ros/cx": 321.04638671875
    "map_ros/cy": 243.44969177246094
    "map_ros/fx": 387.229248046875
    "map_ros/fy": 387.229248046875
    "map_ros/depth_filter_maxdist": 5.0
    "map_ros/depth_filter_mindist": 0.2
    "map_ros/depth_filter_margin": 2.0
    "map_ros/k_depth_scaling_factor": 1000.0
    "map_ros/skip_pixel": 2
    "map_ros/esdf_slice_height": 0.3
    "map_ros/visualization_truncate_height": 3.09
    "map_ros/visualization_truncate_low": -2.0
    "map_ros/show_occ_time": false
    "map_ros/show_esdf_time": false
    "map_ros/show_all_map": true
    "map_ros/frame_id": "world"

    "manager/max_vel": 3.0
    "manager/max_acc": 2.5
    "manager/accept_vel": 3.5
    "manager/accept_acc": 3.0
    "manager/max_jerk": 4.0
    "manager/dynamic_environment": 0
    "manager/local_segment_length": 6.0
    "manager/clearance_threshold": 0.2
    "manager/control_points_distance": 0.5
    "manager/min_time": true
    "manager/bspline_degree": 3
    "manager/use_geometric_path": false
    "manager/use_kinodynamic_path": true
    "manager/use_topo_path": false
    "manager/use_optimization": true
    "manager/use_active_perception": false

    "search/max_tau": 0.5
    "search/init_max_tau": 1.0
    "search/max_vel": 3.0
    "search/vel_margin": 0.25
    "search/max_acc": 2.5
    "search/w_time": 10.0
    "search/horizon": 7.0
    "search/lambda_heu": 10.0
    "search/resolution_astar": 0.025
    "search/time_resolution": 0.8
    "search/margin": 0.2
    "search/allocate_num": 100000
    "search/check_num": 10
    "search/optimistic": false

    "optimization/ld_smooth": 5.0
    "optimization/ld_dist": 10.0
    "optimization/ld_feasi": 1.0
    "optimization/ld_start": 10.0
    "optimization/ld_end": 10.0
    "optimization/ld_guide": 1.5
    "optimization/ld_waypt": 20.0
    "optimization/ld_view": 0.0
    "optimization/ld_time": 0.1
    "optimization/dist0": 0.4
    "optimization/dist1": 0.0
    "optimization/max_vel": 3.0
    "optimization/max_acc": 2.5
    "optimization/algorithm1": 15
    "optimization/algorithm2": 11
    "optimization/max_iteration_num1": 2
    "optimization/max_iteration_num2": 2000
    "optimization/max_iteration_num3": 200
    "optimization/max_iteration_num4": 200
    "optimization/max_iteration_time1": 0.0001
    "optimization/max_iteration_time2": 0.01
    "optimization/max_iteration_time3": 0.003
    "optimization/max_iteration_time4": 0.003
    "optimization/wnl": 1.0

    "bspline/limit_vel": 3.0
    "bspline/limit_acc": 2.5
    "bspline/limit_ratio": 1.1

    "topo_prm/sample_inflate_x": 1.0
    "topo_prm/sample_inflate_y": 3.5
    "topo_prm/sample_inflate_z": 1.0
    "topo_prm/clearance": 0.2
    "topo_prm/max_sample_time": 0.005
    "topo_prm/max_sample_num": 2000
    "topo_prm/max_raw_path": 300
    "topo_prm/max_raw_path2": 25
    "topo_prm/short_cut_num": 1
    "topo_prm/reserve_num": 6
    "topo_prm/ratio_to_short": 5.5
    "topo_prm/parallel_shortcut": true

    "heading_planner/yaw_diff": 0.08726646259971647
    "heading_planner/half_vert_num": 3
    "heading_planner/lambda1": 2.0
    "heading_planner/lambda2": 1.0
    "heading_planner/max_yaw_rate": 1.0471975511965976
    "heading_planner/w": 10.0
    "heading_planner/weight_type": 0

    "visibility/visib_min": 0.25
    "visibility/max_acc": 2.5
    "visibility/r0": 0.0
    "visibility/forward": 0.5
    "visibility/max_safe_dist": 2.0
    "visibility/safe_margin": 0.5
